version: 2.1

jobs:
  build:
    docker:
      - image: node:18
    steps:
      - checkout
      - run: pnpm install
      - run: pnpm run dev

workflows:
  version: 2
  build_and_test:
    jobs:
      - build