version: 2.1

jobs:
  build:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm install
      - run: node --unhandled-rejections=strict index

workflows:
  version: 2
  build_and_test:
    jobs:
      - build